version: '2'

services:
  vinyl_app:
    image: joene/discogssorter:latest
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      flame.type: application
      flame.name: Vinyl Sorter
      flame.url: ${APP_URL}
      flame.icon: album

networks:
  default:
    external:
      name: npm_network
