version: '3'

services:
  al_web:
    image: bitnami/nginx:1.16
    depends_on:
      - al_app
    volumes:
      - ${DIR_INVOICEPLANE}/app:/app:rw,delegated
      - ${DIR_INVOICEPLANE}/app/application/docker/nginx/site.conf:/opt/bitnami/nginx/conf/vhosts/site.conf:ro
    user: root

  al_app:
    #image: bitnami/php-fpm:7.3
    build:
      context: .
      dockerfile: Dockerfile-php
    restart: always
    volumes:
      - ${DIR_INVOICEPLANE}/app:/app:rw,delegated
      - ${DIR_INVOICEPLANE}/app/application/docker/php/php-dev.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro
    depends_on:
      - al_db

  al_db:
    image: bitnami/mariadb:10.3
    restart: always
    environment: 
      - MARIADB_ROOT_PASSWORD=${DB_RPW}
      - MARIADB_USER=${DB_USR}
      - MARIADB_PASSWORD=${DB_PWD}
      - MARIADB_DATABASE=${DB_DB}
    volumes:
      - ${DIR_INVOICEPLANE}/mariadb/data:/bitnami

networks:
  default:
    external:
      name: npm_network
