version: '3'

services:
  joplin_db:
    image: postgres:13.1
    volumes:
      - ${POSTGRES_DIR}/data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
  joplin_app:
    image: joplin/server:2-beta
    depends_on:
      - joplin_db
    restart: always
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=https://${APP_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=joplin_db
    labels:
      flame.type: application
      flame.name: Joplin
      flame.url: https://${APP_URL}
      flame.icon: notebook
      traefik.enable: true
      traefik.http.routers.joplin.rule: Host(`${APP_URL}`) || Host(`${APP2_URL}`)
      traefik.http.services.joplin.loadbalancer.server.port: 22300

networks:
  default:
    external:
      name: npm_network
