version: '3'

services:
  db:
    image: postgres:13.1
    volumes:
      - ${POSTGRES_DIR}/data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
  app:
    image: joplin/server:2.2.8-beta
    depends_on:
      - db
    ports:
      - ${JOPLIN_PORT}:22300
    restart: unless-stopped
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=${JOPLIN_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
