version: '2.1'

services:
  flame_app:
    image: pawelmalak/flame:latest
    restart: unless-stopped
    volumes:
    - ${DATADIR}/app/data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: npm_network
