version: '2.1'

services:
  flame_app:
    image: pawelmalak/flame:latest
    restart: unless-stopped
    volumes:
    - ${DATADIR}/app/data:/app/data
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.http.routers.flame.rule: Host(`${APP_URL}`)
      traefik.http.services.flame.loadbalancer.server.port: 5005
      traefik.http.routers.flame.middlewares: traefik-forward-auth

networks:
  default:
    external:
      name: npm_network
