version: '2.4'

networks:
  default:
    external:
      name: ${NETWORK}

services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    environment:
    - TZ=${TIMEZONE}
    - PUID=0
    - PGID=0
    volumes:
    - ${DIR_CONFIG}/duplicati/config:/config
    - ${DIR_BACKUP_HOMES}:/source/homes:ro
    logging:
      driver: json-file
      options:
        max-size: "1m"
