version: '3'

services:
  vaultwarden_app:
    image: vaultwarden/server:latest
    restart: always
    environment:
      - ADMIN_TOKEN=${TOKEN}
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - SIGNUPS_ALLOWED=false
    volumes:
      - ${DATADIR}/app:/data
    labels:
      flame.type: application
      flame.name: Vaultwarden
      flame.url: https://${APP_URL}
      flame.icon: safe-square
      traefik.enable: true
      traefik.http.routers.vaultwarden.rule: Host(`${APP_URL}`) || Host(`${APP2_URL}`)
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80

networks:
  default:
    external:
      name: npm_network
