version: "3.1"

networks:
  default:
    external:
      name: npm_network

services:
  ghost-app:
    image: ghost:4-alpine
    volumes:
      - ${DATADIR}/app:/var/lib/ghost/content
    restart: always
    environment:
      url: https://${APP_URL}
      database__client: sqlite3
      useMinFiles: "true"
      compress: "true"
      imageOptimization: "true"
      mail__transport: SMTP
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT}
      mail__options_secure: ${MAIL_SECURE}
    labels:
      flame.type: application
      flame.name: Ghost
      flame.url: https://${APP_URL}
      flame.icon: typewriter
      traefik.enable: true
      traefik.http.routers.ghost.rule: Host(`${APP_URL}`) || Host(`${APP2_URL}`) || Host(`${APP3_URL}`)
      traefik.http.services.ghost.loadbalancer.server.port: 2368
