version: '3'
services:
  npm_app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    depends_on:
      - npm_db
    environment:
      DB_MYSQL_HOST: "npm_db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${MYSQL_USER}"
      DB_MYSQL_PASSWORD: "${MYSQL_PW}"
      DB_MYSQL_NAME: "${MYSQL_DB}"
    volumes:
      - ${DATADIR}/npm/data:/data
      - ${DATADIR}/npm/letsencrypt:/etc/letsencrypt
    labels:
      flame.type: application
      flame.name: Nginx Proxy Manager
      flame.url: ${NPM_URL}
      flame.icon: server-security
  npm_db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOTPW}"
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PW}"
    volumes:
      - ${DATADIR}/db/data:/var/lib/mysql

networks:
  default:
    external:
      name: ${NETWORK}
